services:
  react_usecontext:
    container_name: react_usecontext_${USER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /projects
    ports:
      - 8011:3000
    stdin_open: true
    shm_size: "8gb"
    networks:
      - default
    env_file:
      - ../.env
    command: sh -c "cd /projects/study && npm install && yarn start"

networks:
  default:
    name: ${NET_NAME}
    external: true
